name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: make
      run: make
    - name: artifact
      uses: actions/upload-artifact@v4
      with:
        name: deamon
        path: deamon
  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: dowload artifact
      uses: actions/download-artifact@v4
      with:
        name: deamon
    - name: test download artifact
      run: ls -R
    
  
          
