name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: make
      run: make
    - name: artifact
      uses: actions/upload-artifact@v4
      with:
        name: deamon
        path: deamon
  release:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
    steps:
    - name: dowload artifact
      uses: actions/download-artifact@v4
      with:
        name: deamon
    - name: test download artifact
      run: ls -R
    - name: github release
      id: create-new-release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v0.0.${{ github.run_number }}
        release_name: v0.0.${{ github.run_number }}
    - name: upload release deamon
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create-new-release.outputs.upload_url }}
        asset_path: deamon
        asset_name: released-deamon
  
          
